@startuml
set namespaceSeparator ::

class "flutter_rccontroller_app::app.dart::App" {
  {static} -ThemeProvider _themeProvider
  {static} -LocaleProvider _localeProvider
}

"flutter_rccontroller_app::app.dart::App" o-- "flutter_rccontroller_app::theme_provider.dart::ThemeProvider"
"flutter_rccontroller_app::app.dart::App" o-- "flutter_rccontroller_app::locale_provider.dart::LocaleProvider"

class "flutter_rccontroller_app::app.dart::_SplashTransition" {
  +Animation<double> animation
  +Widget build()
}

"flutter_rccontroller_app::app.dart::_SplashTransition" o-- "flutter::src::animation::animation.dart::Animation<double>"

class "flutter_rccontroller_app::app.dart::_WelcomeSplashPage" {
  +Widget build()
}

class "flutter_rccontroller_app::features::control::control_manager.dart::ControlManager" {
  {static} +ControlManager instance
  -ControlTransport? _transport
  -Timer? _sendTimer
  -bool _lastKnownConnected
  -int _lastSendMs
  -double _driveScale
  -bool _reverseSteering
  -bool _reverseThrottle
  -double _tx
  -double _ty
  -double _sx
  -MotionCommand? _activeMotion
  -double _activeMotionPower
  -GpsTelemetry? _gpsTelemetry
  +ControlTransport? transport
  +double driveScale
  +bool reverseSteering
  +bool reverseThrottle
  +GpsTelemetry? gpsTelemetry
  +bool isConnected
  +void setDriveScale()
  +void setReverseSteering()
  +void setReverseThrottle()
  +void setTransport()
  +dynamic connect()
  +void disconnect()
  +void pauseSending()
  +void sendJoystick()
  +void setMotionCommand()
  -void _startTimer()
  -void _stopTimer()
  -int _minSendIntervalMs()
  -void _markDisconnectedIfNeeded()
}

"flutter_rccontroller_app::features::control::control_manager.dart::ControlManager" o-- "flutter_rccontroller_app::features::control::control_manager.dart::ControlManager"
"flutter_rccontroller_app::features::control::control_manager.dart::ControlManager" o-- "flutter_rccontroller_app::transport::control_transport.dart::ControlTransport"
"flutter_rccontroller_app::features::control::control_manager.dart::ControlManager" o-- "dart::async::Timer"
"flutter_rccontroller_app::features::control::control_manager.dart::ControlManager" o-- "flutter_rccontroller_app::features::control::control_manager.dart::MotionCommand"
"flutter_rccontroller_app::features::control::control_manager.dart::ControlManager" o-- "flutter_rccontroller_app::transport::controller_protocol.dart::GpsTelemetry"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "flutter_rccontroller_app::features::control::control_manager.dart::ControlManager"

class "flutter_rccontroller_app::features::control::control_manager.dart::MotionCommand" {
  +int index
  {static} +List<MotionCommand> values
  {static} +MotionCommand forward
  {static} +MotionCommand backward
  {static} +MotionCommand left
  {static} +MotionCommand right
  {static} +MotionCommand forwardLeft
  {static} +MotionCommand forwardRight
  {static} +MotionCommand backwardLeft
  {static} +MotionCommand backwardRight
  {static} +MotionCommand rotateLeft
  {static} +MotionCommand rotateRight
}

"flutter_rccontroller_app::features::control::control_manager.dart::MotionCommand" o-- "flutter_rccontroller_app::features::control::control_manager.dart::MotionCommand"
"dart::core::Enum" <|-- "flutter_rccontroller_app::features::control::control_manager.dart::MotionCommand"

class "flutter_rccontroller_app::features::control::control_page.dart::ControlPage" {
  +ThemeProvider? themeProvider
  +LocaleProvider? localeProvider
}

"flutter_rccontroller_app::features::control::control_page.dart::ControlPage" o-- "flutter_rccontroller_app::theme_provider.dart::ThemeProvider"
"flutter_rccontroller_app::features::control::control_page.dart::ControlPage" o-- "flutter_rccontroller_app::locale_provider.dart::LocaleProvider"

class "flutter_rccontroller_app::features::settings::settings.dart::SettingsPage" {
  +ThemeProvider? themeProvider
  +LocaleProvider? localeProvider
}

"flutter_rccontroller_app::features::settings::settings.dart::SettingsPage" o-- "flutter_rccontroller_app::theme_provider.dart::ThemeProvider"
"flutter_rccontroller_app::features::settings::settings.dart::SettingsPage" o-- "flutter_rccontroller_app::locale_provider.dart::LocaleProvider"

abstract class "flutter_rccontroller_app::l10n::app_localizations.dart::AppLocalizations" {
  +String localeName
  {static} +LocalizationsDelegate<AppLocalizations> delegate
  {static} +List<LocalizationsDelegate<dynamic>> localizationsDelegates
  {static} +List<Locale> supportedLocales
  +String appTitle
  +String settings
  +String language
  +String back
  +String connection
  +String connectionType
  +String wifi
  +String wifiAp
  +String bluetooth
  +String bluetoothLe
  +String bluetoothReminderBody
  +String bluetoothOpenSettings
  +String ok
  +String connectFirstToSwitch
  +String esp32IpAddress
  +String port
  +String pleaseEnterEsp32Ip
  +String udpConnected
  +String udpConnectTimeout
  +String failedToConnectUdp
  +String connecting
  +String connect
  +String connected
  +String disconnect
  +String disconnected
  +String connectionLost
  +String mainMode
  +String mainModeDescription
  +String changeMode
  +String controlSettings
  +String maxDriveSpeed
  +String reverseStrafeX
  +String leftJoystickHorizontalAxis
  +String reverseForwardBackY
  +String leftJoystickVerticalAxis
  +String appearance
  +String theme
  +String system
  +String light
  +String dark
  +String about
  +String appName
  +String version
  +String hardware
  +String developer
  +String organization
  +String description
  +String appDescription
  +String translation
  +String rotation
  +String movementMatrix
  +String hideMovementMatrix
  +String showMovementMatrix
  +String gpsWaiting
  +String gpsFix
  +String gpsNoFix
  +String gpsLatLabel
  +String gpsLonLabel
  +String gpsSatLabel
  +String gpsSpeedLabel
  +String english
  +String spanish
  +String rememberThis
  +String lockRotation
  +String unlockRotation
  +String preparingControllerInterface
  +String moveForward
  +String moveBackward
  +String moveLeft
  +String moveRight
  +String rotateRightCmd
  +String rotateLeftCmd
  +String moveForwardLeft
  +String moveBackwardLeft
  +String moveForwardRight
  +String moveBackwardRight
  {static} +AppLocalizations? of()
}

"flutter_rccontroller_app::l10n::app_localizations.dart::AppLocalizations" o-- "flutter::src::widgets::localizations.dart::LocalizationsDelegate<AppLocalizations>"

class "flutter_rccontroller_app::l10n::app_localizations.dart::_AppLocalizationsDelegate" {
  +dynamic load()
  +bool isSupported()
  +bool shouldReload()
}

"flutter::src::widgets::localizations.dart::LocalizationsDelegate" <|-- "flutter_rccontroller_app::l10n::app_localizations.dart::_AppLocalizationsDelegate"

class "flutter_rccontroller_app::l10n::app_localizations_en.dart::AppLocalizationsEn" {
  +String appTitle
  +String settings
  +String language
  +String back
  +String connection
  +String connectionType
  +String wifi
  +String wifiAp
  +String bluetooth
  +String bluetoothLe
  +String bluetoothReminderBody
  +String bluetoothOpenSettings
  +String ok
  +String connectFirstToSwitch
  +String esp32IpAddress
  +String port
  +String pleaseEnterEsp32Ip
  +String udpConnected
  +String udpConnectTimeout
  +String failedToConnectUdp
  +String connecting
  +String connect
  +String connected
  +String disconnect
  +String disconnected
  +String connectionLost
  +String mainMode
  +String mainModeDescription
  +String changeMode
  +String controlSettings
  +String maxDriveSpeed
  +String reverseStrafeX
  +String leftJoystickHorizontalAxis
  +String reverseForwardBackY
  +String leftJoystickVerticalAxis
  +String appearance
  +String theme
  +String system
  +String light
  +String dark
  +String about
  +String appName
  +String version
  +String hardware
  +String developer
  +String organization
  +String description
  +String appDescription
  +String translation
  +String rotation
  +String movementMatrix
  +String hideMovementMatrix
  +String showMovementMatrix
  +String gpsWaiting
  +String gpsFix
  +String gpsNoFix
  +String gpsLatLabel
  +String gpsLonLabel
  +String gpsSatLabel
  +String gpsSpeedLabel
  +String english
  +String spanish
  +String rememberThis
  +String lockRotation
  +String unlockRotation
  +String preparingControllerInterface
  +String moveForward
  +String moveBackward
  +String moveLeft
  +String moveRight
  +String rotateRightCmd
  +String rotateLeftCmd
  +String moveForwardLeft
  +String moveBackwardLeft
  +String moveForwardRight
  +String moveBackwardRight
}

"flutter_rccontroller_app::l10n::app_localizations.dart::AppLocalizations" <|-- "flutter_rccontroller_app::l10n::app_localizations_en.dart::AppLocalizationsEn"

class "flutter_rccontroller_app::l10n::app_localizations_es.dart::AppLocalizationsEs" {
  +String appTitle
  +String settings
  +String language
  +String back
  +String connection
  +String connectionType
  +String wifi
  +String wifiAp
  +String bluetooth
  +String bluetoothLe
  +String bluetoothReminderBody
  +String bluetoothOpenSettings
  +String ok
  +String connectFirstToSwitch
  +String esp32IpAddress
  +String port
  +String pleaseEnterEsp32Ip
  +String udpConnected
  +String udpConnectTimeout
  +String failedToConnectUdp
  +String connecting
  +String connect
  +String connected
  +String disconnect
  +String disconnected
  +String connectionLost
  +String mainMode
  +String mainModeDescription
  +String changeMode
  +String controlSettings
  +String maxDriveSpeed
  +String reverseStrafeX
  +String leftJoystickHorizontalAxis
  +String reverseForwardBackY
  +String leftJoystickVerticalAxis
  +String appearance
  +String theme
  +String system
  +String light
  +String dark
  +String about
  +String appName
  +String version
  +String hardware
  +String developer
  +String organization
  +String description
  +String appDescription
  +String translation
  +String rotation
  +String movementMatrix
  +String hideMovementMatrix
  +String showMovementMatrix
  +String gpsWaiting
  +String gpsFix
  +String gpsNoFix
  +String gpsLatLabel
  +String gpsLonLabel
  +String gpsSatLabel
  +String gpsSpeedLabel
  +String english
  +String spanish
  +String rememberThis
  +String lockRotation
  +String unlockRotation
  +String preparingControllerInterface
  +String moveForward
  +String moveBackward
  +String moveLeft
  +String moveRight
  +String rotateRightCmd
  +String rotateLeftCmd
  +String moveForwardLeft
  +String moveBackwardLeft
  +String moveForwardRight
  +String moveBackwardRight
}

"flutter_rccontroller_app::l10n::app_localizations.dart::AppLocalizations" <|-- "flutter_rccontroller_app::l10n::app_localizations_es.dart::AppLocalizationsEs"

class "flutter_rccontroller_app::locale_provider.dart::LocaleProvider" {
  -Locale? _locale
  +Locale? locale
  +void setLocale()
  +void clearLocale()
}

"flutter_rccontroller_app::locale_provider.dart::LocaleProvider" o-- "dart::ui::Locale"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "flutter_rccontroller_app::locale_provider.dart::LocaleProvider"

class "flutter_rccontroller_app::services::network_binding_service.dart::NetworkBindingService" {
  {static} -MethodChannel _channel
  {static} +dynamic bindToWifi()
  {static} +dynamic clearBinding()
  {static} +dynamic isWifiBound()
}

"flutter_rccontroller_app::services::network_binding_service.dart::NetworkBindingService" o-- "flutter::src::services::platform_channel.dart::MethodChannel"

class "flutter_rccontroller_app::theme_provider.dart::ThemeProvider" {
  -ThemeMode _themeMode
  +ThemeMode themeMode
  +void setThemeMode()
}

"flutter_rccontroller_app::theme_provider.dart::ThemeProvider" o-- "flutter::src::material::app.dart::ThemeMode"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "flutter_rccontroller_app::theme_provider.dart::ThemeProvider"

class "flutter_rccontroller_app::transport::ble_transport.dart::BleTransport" {
  {static} +String deviceName
  {static} +Guid serviceUuid
  {static} +Guid rxUuid
  {static} +Guid txUuid
  -BluetoothDevice? _device
  -BluetoothCharacteristic? _rxChar
  -BluetoothCharacteristic? _txChar
  -StreamSubscription<List<int>>? _notifySub
  -bool _connected
  -GpsTelemetry? _gpsTelemetry
  +bool isConnected
  +GpsTelemetry? gpsTelemetry
  +dynamic connect()
  -void _handleNotification()
  -GpsTelemetry _parseGpsPacket()
  +void disconnect()
  +void send()
  +dynamic sendModeCommand()
  +dynamic sendMainModeCommand()
  {static} -Uint8List _buildControlPacket()
  {static} +Uint8List buildControlPacket()
  {static} -int _toInt16()
}

"flutter_rccontroller_app::transport::ble_transport.dart::BleTransport" o-- "flutter_blue_plus_platform_interface::src::guid.dart::Guid"
"flutter_rccontroller_app::transport::ble_transport.dart::BleTransport" o-- "flutter_blue_plus::flutter_blue_plus.dart::BluetoothDevice"
"flutter_rccontroller_app::transport::ble_transport.dart::BleTransport" o-- "flutter_blue_plus::flutter_blue_plus.dart::BluetoothCharacteristic"
"flutter_rccontroller_app::transport::ble_transport.dart::BleTransport" o-- "dart::async::StreamSubscription<List<int>>"
"flutter_rccontroller_app::transport::ble_transport.dart::BleTransport" o-- "flutter_rccontroller_app::transport::controller_protocol.dart::GpsTelemetry"
"flutter_rccontroller_app::transport::control_transport.dart::ControlTransport" <|-- "flutter_rccontroller_app::transport::ble_transport.dart::BleTransport"

class "flutter_rccontroller_app::transport::controller_protocol.dart::GpsTelemetry" {
  +bool valid
  +double latitude
  +double longitude
  +double altitude
  +double speedKmph
  +int satellites
  +int ageMs
  +DateTime receivedAt
}

class "flutter_rccontroller_app::transport::controller_protocol.dart::ControllerMode" {
  +int index
  {static} +List<ControllerMode> values
  {static} +ControllerMode wifiAp
  {static} +ControllerMode ble
}

"flutter_rccontroller_app::transport::controller_protocol.dart::ControllerMode" o-- "flutter_rccontroller_app::transport::controller_protocol.dart::ControllerMode"
"dart::core::Enum" <|-- "flutter_rccontroller_app::transport::controller_protocol.dart::ControllerMode"

abstract class "flutter_rccontroller_app::transport::control_transport.dart::ControlTransport" {
  +bool isConnected
  +GpsTelemetry? gpsTelemetry
  +dynamic connect()
  +void disconnect()
  +void send()
  +dynamic sendModeCommand()
  +dynamic sendMainModeCommand()
}

"flutter_rccontroller_app::transport::control_transport.dart::ControlTransport" o-- "flutter_rccontroller_app::transport::controller_protocol.dart::GpsTelemetry"

class "flutter_rccontroller_app::transport::udp_transport.dart::UdpTransport" {
  +String ip
  +int port
  -RawDatagramSocket? _socket
  -StreamSubscription<RawSocketEvent>? _socketSub
  -Timer? _healthTimer
  -bool _healthCheckInProgress
  -bool _initialized
  -InternetAddress? _targetAddress
  -int? _targetPort
  -GpsTelemetry? _gpsTelemetry
  +bool isConnected
  +GpsTelemetry? gpsTelemetry
  +dynamic connect()
  +void disconnect()
  +dynamic sendModeCommand()
  +dynamic sendMainModeCommand()
  -void _startHealthMonitor()
  +void send()
  {static} +String buildSendPayload()
  -GpsTelemetry _parseGpsPacket()
}

"flutter_rccontroller_app::transport::udp_transport.dart::UdpTransport" o-- "dart::io::RawDatagramSocket"
"flutter_rccontroller_app::transport::udp_transport.dart::UdpTransport" o-- "dart::async::StreamSubscription<RawSocketEvent>"
"flutter_rccontroller_app::transport::udp_transport.dart::UdpTransport" o-- "dart::async::Timer"
"flutter_rccontroller_app::transport::udp_transport.dart::UdpTransport" o-- "dart::io::InternetAddress"
"flutter_rccontroller_app::transport::udp_transport.dart::UdpTransport" o-- "flutter_rccontroller_app::transport::controller_protocol.dart::GpsTelemetry"
"flutter_rccontroller_app::transport::control_transport.dart::ControlTransport" <|-- "flutter_rccontroller_app::transport::udp_transport.dart::UdpTransport"


@enduml